// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXmPId_GYCnCtVzY93feBe8pcm-i0Q0q4',
    appId: '1:370834859443:web:b0958d4bd30e66fcc557c6',
    messagingSenderId: '370834859443',
    projectId: 'flutterharjoitus',
    authDomain: 'flutterharjoitus.firebaseapp.com',
    databaseURL: 'https://flutterharjoitus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterharjoitus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs3_OmK_HfqVAPwRbswfUA9SL8SkQ3gs0',
    appId: '1:370834859443:android:e7ef5471f1a2c3cdc557c6',
    messagingSenderId: '370834859443',
    projectId: 'flutterharjoitus',
    databaseURL: 'https://flutterharjoitus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterharjoitus.appspot.com',
  );
}
